deploy:
  - provider: GitHub
    release: "[Release] ak1-radio $(VERSION_NAME)"
    tag: $(VERSION_NAME)
    artifact: ak1-radio-$(VERSION_NAME).zip
    draft: true
    prerelease: false
    auth_token: $(github_auth)
    on:
      APPVEYOR_REPO_TAG: true
    description: "vMenu version $(VERSION_NAME)."
on_success:
  - cmd: appveyor/on_success.bat
on_failure:
  - cmd: appveyor/on_failure.bat
